services:
  mint-redis:
    image: redis:8.0
    ports:
      - 6379:6379
    volumes:
      - mint-data:/data
    container_name: mint-redis
  mint-frontend:
    image: ghcr.io/mrc-ide/mint-frontend:${FRONTEND_REF:-main}
    pull_policy: always
    ports:
      - 127.0.0.1:3000:3000
    environment:
      - REDIS_URL=redis://mint-redis:6379
      - PUBLIC_API_URL=http://mint-api:8000
      - ORIGIN=http://127.0.0.1:3000
    depends_on:
      - mint-redis
      - mint-api
  mint-api:
    image: ghcr.io/mrc-ide/mint-api:${API_REF:-main}
    pull_policy: always
    container_name: mint-api
    ports:
      - 8000:8000
volumes:
  mint-data:
